### ISSUE TITLE
swaggerMeta cannot be executed with JDK 11

### ISSUE THREAD

**Issue by alexandervanhecke** [y-yu/sbt-swagger-meta#4]
Using JDK 11 : 

```
[error] java.lang.IllegalArgumentException: Unsupported class file major version 55
[error] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
[error] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:148)
[error] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:136)
[error] 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:237)
[error] 	at org.clapper.classutil.asm.ClassFile$.load(ClassFinderImpl.scala:259)
[error] 	at org.clapper.classutil.ClassFinder.classData(ClassFinder.scala:428)
[error] 	at org.clapper.classutil.ClassFinder.$anonfun$processDirectory$3(ClassFinder.scala:412)
[error] 	at scala.collection.immutable.Stream.map(Stream.scala:418)
[error] 	at org.clapper.classutil.ClassFinder.processDirectory(ClassFinder.scala:410)
[error] 	at org.clapper.classutil.ClassFinder.findClassesIn(ClassFinder.scala:337)
[error] 	at org.clapper.classutil.ClassFinder.find(ClassFinder.scala:324)
[error] 	at org.clapper.classutil.ClassFinder.getClasses(ClassFinder.scala:315)
[error] 	at sbtswaggermeta.SbtSwaggerMeta$.$anonfun$swaggerMetaTask$1(SbtSwaggerMeta.scala:102)
[error] 	at sbtswaggermeta.SbtSwaggerMeta$.$anonfun$swaggerMetaTask$1$adapted(SbtSwaggerMeta.scala:82)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (swaggerMeta) java.lang.IllegalArgumentException: Unsupported class file major version 55
```

Is there any way the objectweb asm dependency can be upgraded to include support for jdk 11? 

thanks,

**Comment by alexandervanhecke** [comment]
I have created a pull request for this : https://github.com/y-yu/sbt-swagger-meta/pull/5

tested this locally and it works fine.
